# Introducere in Data Science - Tema 1 Laborator 2
## Grupa
### 10LF381
## Membri
### - Bucur Robert-Adrian
### - Bogdan Gheorghe-Nicolae

# Exercitii functii
Nota: aceste exercitii nu se puncteaza.
## Exercitiul 1
Sa se scrie o functie care primeste ca parametru o lista de numere si returneaza un tuplu continand: suma elementelor si diferenta maxima dintre elementele listei.

In [10]:
from typing import List

In [11]:
def sum_diff_max(lista : List[float]) -> (float, float):
    '''Function for summing the elements in a list and calculating the maximum difference
    :param lista: the list for summing up the elements and calculate the difference
    :return: tuple of two values of int which represents the sum and the diff'''
    
    return (sum(lista), max(lista) - min(lista))

In [12]:
sum_diff_max([1,2,3,4,5])

(15, 4)

## Exercitiul 2
Scrieti o functie care preia doua liste si returneaza True daca cele doua liste de numere contin cel putin $k$ elemente comune ($k \ge 1$ dat ca parametru intreg, valoare implicita 1), False altfel.

In [13]:
def same_k_elements(list1 : List[int], list2 : List[int], k : int = 1) -> bool:
    '''Function to verify if the intersection of two lists has at least k elements
    :param list1: the first list
    :param list2: the second list
    :return: True if the condition is verified and False else'''
    set1, set2 = set(list1), set(list2)
    return len(set1.intersection(set2)) >= k

In [14]:
same_k_elements([1,2,3,4],[2,3,4,5,6],4)

False

## Exercitiul 3
Sa se scrie o functie care determina daca o lista contine cuvinte reprezentand doar numere intregi (optional: numere fractionare, scrise sub forma parte intreaga, optional urmata de punct zecimal, optional urmata de parte fractionara: 1, 2., 13.14) (Puteti folosi modulul re pentru lucrul cu expresii regulate.) Functia trebuie sa testeze daca:
- elementele din lista sunt stringuri
- fiecare din stringuri este un numar

In [15]:
def validate_list_to_integer(list_str : List[str]) -> bool:
    '''Function to verify if all words from list_str are integers
    :param list_str: list of words for verification
    :return: True if the condition is verified and False else'''
    for item in list_str:
        if not item.isdigit():
            return False
    return True

In [16]:
validate_list_to_integer(['1','2','3','hello'])

False

## Exercitiul 4
Sa se scrie o functie care returneaza numarul de vocale si de consoane dintr-un parametru dat - rezultatul returnat de functie este tuplu cu doua valori. Cuvantul se va converti la litere mici in interiorul functiei.

In [17]:
def number_of_vowel_consonants(word : str) -> (int, int):
    '''Function to count the number of vowels and consonants in a word
    :param word: the string for counting the vowels and consonants
    :return: tuple containing the number of vowels and consonants'''
    word.lower()
    vowels = ['a', 'e', 'i', 'o', 'u']
    number_of_vowels = 0
    number_of_consonants = 0
    for character in word:
        if character in vowels:
            number_of_vowels += 1
        else:
            number_of_consonants += 1
    return (number_of_vowels, number_of_consonants)

In [18]:
number_of_vowel_consonants('Hammer')

(2, 4)

## Exercitiul 5
Sa se scrie o functie care primind o lista de dictionare, returneaza True daca toate dictionarele contin cel putin $n$ elemente, $n$ transmis ca parametru, False altfel.

In [19]:
def n_elements_dicts(list_dict : List[dict],n : int = 1) -> bool:
    '''Function to verify each dictionar in a list of dictionaries has at least n elements
    :param list_dict: the list of dictionaries
    :param n: the minimum number of elements which each dictionar must contain
    :return: True if the condition is verified and False else'''
    for dictionar in list_dict:
        if len(dictionar) < n:
            return False
    return True

In [20]:
list_dict = [{1 : 'ana', 2 : 'are', 3 : 'mere'},
            {'ana' : 'are', 'mere' : 'pere'},
            {1 : 2, 3 : 4, 5 : 6, 7 : 8, 9 : 10}]
n_elements_dicts(list_dict,n=3)

False

# Exercitiul 6
Sa se scrie o functie recursiva care sa faca ridicarea la putere a unui numar, astfel: $$
a^n = \begin{cases}
a \space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space \text{ , daca }n=1
\\
\left(a^{n//2}\right)^2 \space\space\space\space\space\space\space\space\space \text{ , daca } n \text{ e par}
\\
\left(a^{n//2}\right)^2 \cdot a \space\space\space\space \text{ , daca } n \text{ e impar}, n > 1
\\
\end{cases}
$$ unde prin $n//2$ se reprezinta catul impartirii intregi intre $n$ si 2.

In [21]:
def power_recursive(a : int, n : int = 1) -> int:
    '''Function to calculate a at power n recursive
    :param a: an integer; the base
    :param n: an integere; the power
    :return: an integer; the result of a**n'''
    if n == 1:
        return a
    if n % 2 == 0:
        return power_recursive(a, n//2) ** 2
    return (power_recursive(a, n//2) ** 2) * a

In [22]:
power_recursive(a=2,n=3)

8

# Exercitii NumPy
Nota: in rezolvarea exercitiilor se vor folosi cat mai mult functii NumPy vectorizate. Functiile scrise de voi vor fi documentate cu docstrings (tutoriale: Docstrings in Python, urmati NumPy Style Python Docstrings). Folositi type annotations. Utilizati doar pachetele NumPy.

In [3]:
import numpy as np

## Exercitiul 1
(0.5 puncte) Pentru un vector NumPy dat, sa se determine care sunt elementele unice, in ordine descrescatoare. Exemplu: pentru x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4]) functia scrisa de dvs va intoarce rezultatul [ 5,  3,  2,  1, -3, -4].

In [24]:
def sorted_desc_unique_items(x : np.array) -> np.array:
    '''Function to sort the descending, unique items of a np.array
    :param x: the np.array to sort
    :return: the sorted np.array'''
    return sorted(np.unique(x),reverse=True)

In [25]:
x = np.array([-4, 3, 5, 3, 2, 1, -3, -4, 2, -4])
sorted_desc_unique_items(x)

[5, 3, 2, 1, -3, -4]

## Exercitiul 2
(0.5 puncte) Pentru un vector NumPy dat, sa se determine care e elementul cel mai frecvent si cel mai putin frecvent (tuplu de 2 valori). Daca exista mai multe numere cele mai frecvente (cele mai putin frecvente), se va raporta oricare din ele. Exemplu: pentru x = np.array([-4, 3,  5, 3, 2, 1, -3, -4, 2, -4]) functia scrisa de dvs va intoarce rezultatul (-4, -3).

In [8]:
def most_least_frequent(x : np.array) -> (int, int):
    '''Function to determin which element appears the most and which element appears the least in a np.array
    :param x: the np.array
    :return: a tuple with the two elements'''
    (unique_values, counts) = np.unique(x, return_counts=True)
    max_index, min_index = np.argmax(counts), np.argmin(counts)
    return (unique_values[max_index], unique_values[min_index])

In [9]:
x = np.array([-4, 3, 5, 3, 2, 1, -3, -4, 2, -4])
most_least_frequent(x)

(-4, -3)

## Exercitiul 3
(0.5 puncte) Plecand de la o matrice, sa se scrie o functie care returneaza vectorul minimelor de pe linii si vectorul maximelor de pe coloane. Exemplu: pentru matricea mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]]) functia va returna tuplul de vectori: (array([ 1, -4,  3]), array([ 3, 10,  3,  4])). Indicatie: folositi-va de parametrul axis.

In [36]:
def min_line_max_col(mat : np.array) -> (np.array, np.array):
    '''Function to determin the minimum value of each line and 
    maximum value of each column in a matrix like np.array
    :param mat: the matrix like np.aprray
    :return: a tuple with the two np.arrays'''
    min_line = np.amin(mat, axis=1)
    max_col = np.amax(mat, axis=0)
    return (min_line, max_col)

In [37]:
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
min_line_max_col(mat)

(array([ 1, -4,  3]), array([ 3, 10,  3,  4]))

## Exercitiul 4
(0.5 puncte) Pentru o matrice de numere, sa se determine produsul elementelor pe linii sau de pe coloane, in functie de valoarea unui parametru boolean compute_on_lines. Exemplu: pentru matricea mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]]) si parametrul compute_on_lines=True, functia va returna vectorul [ 24  24 360], iar pentru compute_on_lines=False se va returna [  3 -40  27 -64].

In [38]:
def multiplication_line_column(mat : np.array, compute_on_lines : bool = True) -> np.array:
    '''Function to calculate the multiplication of elements on lines or columns depends on compute_on_lines
    :param mat: the matrix like np.aprray
    :param compute_on_lines: if True the multiplication is calculated on lines, else is calculated on columns
    :return: the array with the result of multiplication on each line or column'''
    if compute_on_lines is True:
        return np.prod(mat, axis=1)
    return np.prod(mat, axis=0)

In [42]:
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
print(multiplication_line_column(mat))
multiplication_line_column(mat,compute_on_lines=False)

[ 24  24 360]


array([  3, -40,  27, -64])

## Exercitiul 5
(0.5 puncte) Determinati daca macar unul din elementele unei matrice a este mai mare decat cel de pe pozitia corespondenta din b (adica daca avem macar o pereche de indecsi (i, j) pentru care a[i, j] > b[i, j]). Daca da, se va returna o astfel de pereche de indecsi; daca nu, se va returna None.

In [13]:
from typing import Optional, Tuple

In [33]:
def element_a_gt_element_b(a : np.array, b : np.array) -> Optional[Tuple[int,int]]:
    '''Function to determin a pair of indices (i,j) for which a[i,j]>b[i,j];
    if does not exit such a pair the function returns None
    :param a: the first matrix
    :param b: the second matrix
    :return: a tuple of ints which represents indices in matrix or None'''
    assert a.shape == b.shape , 'The two matrices have not the same shape'
    mat_indices = np.argwhere(a > b)
    if len(mat_indices):
        return (mat_indices[0,0], mat_indices[0,1])
    return None

In [34]:
a = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
b = np.array([[1, -2, 3, -4], [1, 2, 3, 4], [3, 10, 3, 4]])
indices = element_a_gt_element_b(a,b) 
if indices is not None:
    print(indices)
else:
    print("There isn't a value!")

(0, 1)


## Exercitiul 6
(0.5 puncte) Construiti o functie care, primind o matrice, determina pe ce pozitii se afla valorile in afara unui interval [min, max] dat prin parametri.

In [117]:
def elements_out_range_min_max(mat : np.array, range_min_max : (int, int)) -> np.array:
    '''Function to determin element's indices which don't belong to the range [min_range,max_range]
    :param mat: the matrix to look in
    :param min_range: the minimum value of the range
    :param max_range: the maximum value of the range
    :return: a np.array of indices'''
    return np.concatenate((np.argwhere(mat < range_min_max[0]),np.argwhere(mat > range_min_max[1])))

In [118]:
mat = np.array([[1, 2, 3, 4], [1, -2, 3, -4], [3, 10, 3, 4]])
elements_out_range_min_max(mat, (0, 3))

array([[1, 1],
       [1, 3],
       [0, 3],
       [2, 1],
       [2, 3]])

## Exercitiul 7
(1 punct) Se considera vectorul: a = np.array([230, 10, 284, 39, 76]). Folosind indexarea logica, sa se inmulteasca elementele din vector care sunt mai mici ca 100 cu 2 (restul raman neschimbate). Folosind ciclare, sa se aplice aceeasi operatie pana cand toate elementele devin mai mari ca 100. Sa se afiseze din vectorul final elementele care sunt mai mari de 150 si mai mici de 200.

In [36]:
def double_elements_under_100(a : np.array) -> np.array:
    '''Function to double the elements less than 100 in a np.array
    :param a: the input np.array
    :return: the result np.array'''
    while any(a < 100):
        a[a < 100] *= 2
    return a

In [38]:
a = np.array([230, 10, 284, 39, 76])
double_elements_under_100(a)
print(a[a[a > 150] < 200])

[160 156 152]


## Exercitiul 8
(1 punct) Sa se scrie o functie `pair_max` care preia doi vectori de aceeasi lungime si returneaza maximele pe pozitiile corespunzatoare:
```
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)
# iesire dorita: 
array([  4,   7,   9, 100, 300, 230,   3])
```
Functia va verifica cu `assert` ca vectorii au lungimi egale.

In [42]:
def pair_max(a : np.array, b : np.array) -> np.array:
    '''Function to determin maximum value on each position in two np.arrays
    :param a: the first np.array
    :param b: the second np.array
    :return: the resulting np.array'''
    assert len(a) == len(b) , 'The two arrays have not the same length!'
    return np.maximum(a, b)

In [43]:
a = np.array([3, 7, 9, 13, -10, 200, 3])
b = np.array([4, 5, -9, 100, 300, 230, 1])
pair_max(a, b)

array([  4,   7,   9, 100, 300, 230,   3])

## Exercitiul 9
(1 punct) Descarcati setul de date Iris de la adresa 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', si incarcati-l intr-o matrice NumPy, folosind np.genfromtxt. Alegeti aleator 10 pozitii in matricea de 150 linii si 4 coloane (omiteti ultima coloana, de tip text), setati aceste valori pe NaN. Construiti o functie care, primind la intrare o matrice, returneaza un tuplu cu indicii de linii respectiv de coloane in care se gasesc valori NaN.

In [179]:
def detect_NaN(mat : np.array): ##-> (List[int], List[int]):
    '''Function to detect on which lines and on which columns are values of NaN
    :param mat: the matrix to look in
    :return: a tuple of lists of lines and columns indices'''
    np.argwhere(mat == 100)
    return 

In [181]:
b = np.array([[3, 7, 9, 13, -10, 100, 3], [4, 5, -9, 100, 100, 230, 1], [230, 10, 284, 39, 76, 100, 13]])
detect_NaN(b)
print('Nefinalizat')

Nefinalizat


## Exercitiul 10
(1 punct) Sa se construiasca o functie care returneaza cele mai mici k valori dintr-un vector de cel putin k elemente, impreuna cu pozitiile lor.

In [54]:
def k_mins(a : np.array, k : int) -> Tuple[np.array, np.array]:
    '''Function to determin the minimum k items in np.array
    :param a: the array to look in
    :param k: the number of values
    :return: the minimum values with their position'''
    assert len(a) >= k , 'The np.array does not have at least k elements'
    return (a[np.argpartition(a, k)[:k]], np.argpartition(a, k)[:k])

In [55]:
a = np.array([69, 38, 60, 91, 4, 81, 54, 45, 13, 95])
k_mins(a, 4)

(array([38, 45,  4, 13]), array([1, 7, 4, 8]))